/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MyApp as MyProgress
} from './components/my-app/my-progress';

declare global {
  interface HTMLMyProgressElement extends MyProgress, HTMLElement {
  }
  var HTMLMyProgressElement: {
    prototype: HTMLMyProgressElement;
    new (): HTMLMyProgressElement;
  };
  interface HTMLElementTagNameMap {
    "my-progress": HTMLMyProgressElement;
  }
  interface ElementTagNameMap {
    "my-progress": HTMLMyProgressElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-progress": JSXElements.MyProgressAttributes;
    }
  }
  namespace JSXElements {
    export interface MyProgressAttributes extends HTMLAttributes {
      loadinMessage?: string;
      progress?: number;
    }
  }
}

